# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zSh8SUWFxS83DzLsjTZzgN22I4OKkyx6
"""

import pandas as pd

royhat={
    "Ism":["Dilroza","Ruxshona","Zahro"],
    "familiya": ["valiyeva","ergashrva","parpiyeva" ],
    "Yoshi": [19,19,18 ],
    "Manzili":["qoqon","fargona","dangara"],
    "Jinsi":["ayol","ayol","ayol"]
}
baza=pd.DataFrame(royhat)
print(baza)

filter=baza[baza['Yoshi']<=19]
print(filter)

filter=baza[baza['Manzili']=="fargona"]
print(filter)

yildankeyin=baza['Yoshi']+30
print(filter)

titanik=pd.read_csv("/content/titanic.csv")
print(titanik)

filter=titanik[titanik['Sex']=="female"]
print(filter)

filter=titanik[titanik['Age']>=15]
print(filter)

filter=titanik[titanik['Ticket']=="211536"]
print(filter)